import Vars, StaticImages, Achievements
from GeneralFunctions import Clear, Wait
def Driving(z = ""):
  if z != "skip":
    Vars.ToDrive = True
    while Vars.ToDrive == True:
      print("")
      print("")
      print("")
      print("")
      print("")
      print("")
      print("")
      print("")
      print("")
      Clear(.025)
      print(" ")
      print(" ")
      print(" ")
      print(" ")
      print("▏")
      print("▏")
      print("▏")
      print(" ")
      print(" ")
      Clear(.025)
      print(" ")
      print(" ")
      print(" ")
      print(" ")
      print("▌")
      print("▌")
      print("▌")
      print(" ")
      print(" ")
      Clear(.025)
      print(" ")
      print(" ")
      print(" ")
      print(" ")
      print("█")
      print("█")
      print("█")
      print(" ")
      print(" ")
      Clear(.025)
      print("  ")
      print("  ")
      print("  ")
      print("▙ ")
      print("██")
      print("██")
      print("██")
      print("  ")
      print("  ")
      Clear(.025)
      print("   ")
      print("   ")
      print("▙  ")
      print("█▙ ")
      print("███")
      print("███")
      print("███")
      print("   ")
      print("   ")
      Clear(.025)
      print("    ")
      print("    ")
      print("▙   ")
      print("▁█▙ ")
      print("▕███")
      print("▕███")
      print("▁███")
      print("▙   ")
      print("▛   ")
      Clear(.025)
      print("     ")
      print("     ")
      print("█▙   ")
      print("▁▁█▙ ")
      print("▗▕███")
      print(" ▕███")
      print("▁▁███")
      print("█▙   ")
      print("█▛   ")
      Clear(.025)
      print("      ")
      print("      ")
      print("██▙   ")
      print("▁▁▁█▙ ")
      print(" ▗▕███")
      print("  ▕███")
      print("▁▁▁███")
      print("▟█▙   ")
      print("▜█▛   ")
      Clear(.025)
      print("       ")
      print("       ")
      print("███▙   ")
      print("█▁▁▁█▙ ")
      print("█ ▗▕███")
      print("█  ▕███")
      print("█▁▁▁███")
      print(" ▟█▙   ")
      print(" ▜█▛   ")
      Clear(.025)
      print("        ")
      print("        ")
      print(" ███▙   ")
      print(" █▁▁▁█▙ ")
      print("██ ▗▕███")
      print("██  ▕███")
      print("██▁▁▁███")
      print("  ▟█▙   ")
      print("  ▜█▛   ")
      Clear(.025)
      print("         ")
      print("         ")
      print("  ███▙   ")
      print("  █▁▁▁█▙ ")
      print("███ ▗▕███")
      print("███  ▕███")
      print("███▁▁▁███")
      print("   ▟█▙   ")
      print("   ▜█▛   ")
      Clear(.025)
      print("          ")
      print("          ")
      print("   ███▙   ")
      print("   █▁▁▁█▙ ")
      print("████ ▗▕███")
      print("████  ▕███")
      print("████▁▁▁███")
      print("    ▟█▙   ")
      print("    ▜█▛   ")
      Clear(.025)
      print("           ")
      print("           ")
      print("    ███▙   ")
      print("    █▁▁▁█▙ ")
      print("█████ ▗▕███")
      print("█████  ▕███")
      print("█████▁▁▁███")
      print("     ▟█▙   ")
      print("     ▜█▛   ")
      Clear(.025)
      print("            ")
      print("            ")
      print("     ███▙   ")
      print("     █▁▁▁█▙ ")
      print("██████ ▗▕███")
      print("██████  ▕███")
      print("██████▁▁▁███")
      print("      ▟█▙   ")
      print("      ▜█▛   ")
      Clear(.025)
      print("             ")
      print("             ")
      print("      ███▙   ")
      print("      █▁▁▁█▙ ")
      print("███████ ▗▕███")
      print("███████  ▕███")
      print("███████▁▁▁███")
      print("       ▟█▙   ")
      print("       ▜█▛   ")
      Clear(.025)
      print("              ")
      print("              ")
      print("       ███▙   ")
      print("       █▁▁▁█▙ ")
      print("████████ ▗▕███")
      print("████████  ▕███")
      print("████████▁▁▁███")
      print("        ▟█▙   ")
      print("        ▜█▛   ")
      Clear(.025)
      print("               ")
      print("               ")
      print("        ███▙   ")
      print("        █▁▁▁█▙ ")
      print("█████████ ▗▕███")
      print("█████████  ▕███")
      print("█████████▁▁▁███")
      print("         ▟█▙   ")
      print("         ▜█▛   ")
      Clear(.025)
      print("                ")
      print("                ")
      print("         ███▙   ")
      print("         █▁▁▁█▙ ")
      print("██████████ ▗▕███")
      print("██████████  ▕███")
      print("██████████▁▁▁███")
      print("          ▟█▙   ")
      print("          ▜█▛   ")
      Clear(.025)
      print("                 ")
      print("                 ")
      print("          ███▙   ")
      print("          █▁▁▁█▙ ")
      print("███████████ ▗▕███")
      print("███████████  ▕███")
      print("███████████▁▁▁███")
      print("           ▟█▙   ")
      print("           ▜█▛   ")
      Clear(.025)
      print("                  ")
      print("                  ")
      print("           ███▙   ")
      print("           █▁▁▁█▙ ")
      print("████████████ ▗▕███")
      print("████████████  ▕███")
      print("████████████▁▁▁███")
      print("            ▟█▙   ")
      print("            ▜█▛   ")
      Clear(.025)
      print("                   ")
      print("                   ")
      print("            ███▙   ")
      print("            █▁▁▁█▙ ")
      print("█████████████ ▗▕███")
      print("█████████████  ▕███")
      print("█████████████▁▁▁███")
      print("             ▟█▙   ")
      print("             ▜█▛   ")
      Clear(.025)
      print("                    ")
      print("                    ")
      print("             ███▙   ")
      print("             █▁▁▁█▙ ")
      print("██████████████ ▗▕███")
      print("██████████████  ▕███")
      print("██████████████▁▁▁███")
      print("▙             ▟█▙   ")
      print("▛             ▜█▛   ")
      Clear(.025)
      print("                     ")
      print("                     ")
      print("              ███▙   ")
      print("              █▁▁▁█▙ ")
      print("███████████████ ▗▕███")
      print("███████████████  ▕███")
      print("███████████████▁▁▁███")
      print("█▙             ▟█▙   ")
      print("█▛             ▜█▛   ")
      Clear(.025)
      print("                      ")
      print("                      ")
      print("               ███▙   ")
      print("               █▁▁▁█▙ ")
      print("████████████████ ▗▕███")
      print("████████████████  ▕███")
      print("████████████████▁▁▁███")
      print("▟█▙             ▟█▙   ")
      print("▜█▛             ▜█▛   ")
      Clear(.025)
      print("                       ")
      print("                       ")
      print("                ███▙   ")
      print("                █▁▁▁█▙ ")
      print("█████████████████ ▗▕███")
      print("█████████████████  ▕███")
      print("█████████████████▁▁▁███")
      print(" ▟█▙             ▟█▙   ")
      print(" ▜█▛             ▜█▛   ")
      Clear(.025)
      print("                        ")
      print("                        ")
      print("                 ███▙   ")
      print("                 █▁▁▁█▙ ")
      print("██████████████████ ▗▕███")
      print("██████████████████  ▕███")
      print("██████████████████▁▁▁███")
      print("  ▟█▙             ▟█▙   ")
      print("  ▜█▛             ▜█▛   ")
      Clear(.025)
      for frame in range(185):
        frame += 1
        print("                        ".rjust(frame+24))
        print("                        ".rjust(frame+24))
        print("                 ███▙   ".rjust(frame+24))
        print("                 █▁▁▁█▙ ".rjust(frame+24))
        print("██████████████████ ▗▕███".rjust(frame+24))
        print("██████████████████  ▕███".rjust(frame+24))
        print("██████████████████▁▁▁███".rjust(frame+24))
        print("  ▟█▙             ▟█▙   ".rjust(frame+24))
        print("  ▜█▛             ▜█▛   ".rjust(frame+24))
        Clear(.025)
      print("                       ".rjust(209))
      print("                       ".rjust(209))
      print("                 ███▙  ".rjust(209))
      print("                 █▁▁▁█▙".rjust(209))
      print("██████████████████ ▗▕██".rjust(209))
      print("██████████████████  ▕██".rjust(209))
      print("██████████████████▁▁▁██".rjust(209))
      print("  ▟█▙             ▟█▙  ".rjust(209))
      print("  ▜█▛             ▜█▛  ".rjust(209))
      Clear(.025)
      print("                      ".rjust(209))
      print("                      ".rjust(209))
      print("                 ███▙ ".rjust(209))
      print("                 █▁▁▁█".rjust(209))
      print("██████████████████ ▗▕█".rjust(209))
      print("██████████████████  ▕█".rjust(209))
      print("██████████████████▁▁▁█".rjust(209))
      print("  ▟█▙             ▟█▙ ".rjust(209))
      print("  ▜█▛             ▜█▛ ".rjust(209))
      Clear(.025)
      print("                     ".rjust(209))
      print("                     ".rjust(209))
      print("                 ███▙".rjust(209))
      print("                 █▁▁▁".rjust(209))
      print("██████████████████ ▗▕".rjust(209))
      print("██████████████████  ▕".rjust(209))
      print("██████████████████▁▁▁".rjust(209))
      print("  ▟█▙             ▟█▙".rjust(209))
      print("  ▜█▛             ▜█▛".rjust(209))
      Clear(.025)
      print("                    ".rjust(209))
      print("                    ".rjust(209))
      print("                 ███".rjust(209))
      print("                 █▁▁".rjust(209))
      print("██████████████████ ▗".rjust(209))
      print("██████████████████  ".rjust(209))
      print("██████████████████▁▁".rjust(209))
      print("  ▟█▙             ▟█".rjust(209))
      print("  ▜█▛             ▜█".rjust(209))
      Clear(.025)
      print("                   ".rjust(209))
      print("                   ".rjust(209))
      print("                 ██".rjust(209))
      print("                 █▁".rjust(209))
      print("██████████████████ ".rjust(209))
      print("██████████████████ ".rjust(209))
      print("██████████████████▁".rjust(209))
      print("  ▟█▙             ▟".rjust(209))
      print("  ▜█▛             ▜".rjust(209))
      Clear(.025)
      print("                  ".rjust(209))
      print("                  ".rjust(209))
      print("                 █".rjust(209))
      print("                 █".rjust(209))
      print("██████████████████".rjust(209))
      print("██████████████████".rjust(209))
      print("██████████████████".rjust(209))
      print("  ▟█▙             ".rjust(209))
      print("  ▜█▛             ".rjust(209))
      Clear(.025)
      print("                 ".rjust(209))
      print("                 ".rjust(209))
      print("                 ".rjust(209))
      print("                 ".rjust(209))
      print("█████████████████".rjust(209))
      print("█████████████████".rjust(209))
      print("█████████████████".rjust(209))
      print("  ▟█▙            ".rjust(209))
      print("  ▜█▛            ".rjust(209))
      Clear(.025)
      print("                ".rjust(209))
      print("                ".rjust(209))
      print("                ".rjust(209))
      print("                ".rjust(209))
      print("████████████████".rjust(209))
      print("████████████████".rjust(209))
      print("████████████████".rjust(209))
      print("  ▟█▙           ".rjust(209))
      print("  ▜█▛           ".rjust(209))
      Clear(.025)
      print("               ".rjust(209))
      print("               ".rjust(209))
      print("               ".rjust(209))
      print("               ".rjust(209))
      print("███████████████".rjust(209))
      print("███████████████".rjust(209))
      print("███████████████".rjust(209))
      print("  ▟█▙          ".rjust(209))
      print("  ▜█▛          ".rjust(209))
      Clear(.025)
      print("              ".rjust(209))
      print("              ".rjust(209))
      print("              ".rjust(209))
      print("              ".rjust(209))
      print("██████████████".rjust(209))
      print("██████████████".rjust(209))
      print("██████████████".rjust(209))
      print("  ▟█▙         ".rjust(209))
      print("  ▜█▛         ".rjust(209))
      Clear(.025)
      print("             ".rjust(209))
      print("             ".rjust(209))
      print("             ".rjust(209))
      print("             ".rjust(209))
      print("█████████████".rjust(209))
      print("█████████████".rjust(209))
      print("█████████████".rjust(209))
      print("  ▟█▙        ".rjust(209))
      print("  ▜█▛        ".rjust(209))
      Clear(.025)
      print("            ".rjust(209))
      print("            ".rjust(209))
      print("            ".rjust(209))
      print("            ".rjust(209))
      print("████████████".rjust(209))
      print("████████████".rjust(209))
      print("████████████".rjust(209))
      print("  ▟█▙       ".rjust(209))
      print("  ▜█▛       ".rjust(209))
      Clear(.025)
      print("           ".rjust(209))
      print("           ".rjust(209))
      print("           ".rjust(209))
      print("           ".rjust(209))
      print("███████████".rjust(209))
      print("███████████".rjust(209))
      print("███████████".rjust(209))
      print("  ▟█▙      ".rjust(209))
      print("  ▜█▛      ".rjust(209))
      Clear(.025)
      print("          ".rjust(209))
      print("          ".rjust(209))
      print("          ".rjust(209))
      print("          ".rjust(209))
      print("██████████".rjust(209))
      print("██████████".rjust(209))
      print("██████████".rjust(209))
      print("  ▟█▙     ".rjust(209))
      print("  ▜█▛     ".rjust(209))
      Clear(.025)
      print("         ".rjust(209))
      print("         ".rjust(209))
      print("         ".rjust(209))
      print("         ".rjust(209))
      print("█████████".rjust(209))
      print("█████████".rjust(209))
      print("█████████".rjust(209))
      print("  ▟█▙    ".rjust(209))
      print("  ▜█▛    ".rjust(209))
      Clear(.025)
      print("        ".rjust(209))
      print("        ".rjust(209))
      print("        ".rjust(209))
      print("        ".rjust(209))
      print("████████".rjust(209))
      print("████████".rjust(209))
      print("████████".rjust(209))
      print("  ▟█▙   ".rjust(209))
      print("  ▜█▛   ".rjust(209))
      Clear(.025)
      print("       ".rjust(209))
      print("       ".rjust(209))
      print("       ".rjust(209))
      print("       ".rjust(209))
      print("███████".rjust(209))
      print("███████".rjust(209))
      print("███████".rjust(209))
      print("  ▟█▙  ".rjust(209))
      print("  ▜█▛  ".rjust(209))
      Clear(.025)
      print("      ".rjust(209))
      print("      ".rjust(209))
      print("      ".rjust(209))
      print("      ".rjust(209))
      print("██████".rjust(209))
      print("██████".rjust(209))
      print("██████".rjust(209))
      print("  ▟█▙ ".rjust(209))
      print("  ▜█▛ ".rjust(209))
      Clear(.025)
      print("     ".rjust(209))
      print("     ".rjust(209))
      print("     ".rjust(209))
      print("     ".rjust(209))
      print("█████".rjust(209))
      print("█████".rjust(209))
      print("█████".rjust(209))
      print("  ▟█▙".rjust(209))
      print("  ▜█▛".rjust(209))
      Clear(.025)
      print("    ".rjust(209))
      print("    ".rjust(209))
      print("    ".rjust(209))
      print("    ".rjust(209))
      print("████".rjust(209))
      print("████".rjust(209))
      print("████".rjust(209))
      print("  ▟█".rjust(209))
      print("  ▜█".rjust(209))
      Clear(.025)
      print("   ".rjust(209))
      print("   ".rjust(209))
      print("   ".rjust(209))
      print("   ".rjust(209))
      print("███".rjust(209))
      print("███".rjust(209))
      print("███".rjust(209))
      print("  ▟".rjust(209))
      print("  ▜".rjust(209))
      Clear(.025)
      print("  ".rjust(209))
      print("  ".rjust(209))
      print("  ".rjust(209))
      print("  ".rjust(209))
      print("██".rjust(209))
      print("██".rjust(209))
      print("██".rjust(209))
      print("  ".rjust(209))
      print("  ".rjust(209))
      Clear(.025)
      print(" ".rjust(209))
      print(" ".rjust(209))
      print(" ".rjust(209))
      print(" ".rjust(209))
      print("█".rjust(209))
      print("█".rjust(209))
      print("█".rjust(209))
      print(" ".rjust(209))
      print(" ".rjust(209))
      Clear(.025)
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      print("".rjust(209))
      Clear(.025)
      if Vars.DriveCount == 0 and "drivenToMadness" not in Achievements.Unlocked:
        print("You hear strange noises coming from a house nearby.".center(210))
        print("Keep Driving / Investigate / Go Home".center(210))
        ConDrive(1)
      elif Vars.DriveCount == 0 and "drivenToMadness" in Achievements.Unlocked:
        print("You hear strange noises coming from a house nearby.".center(210))
        print("Investigate / Go Home".center(210))
        ConDrive(2)
      elif Vars.DriveCount <= 3:
        print("Keep Driving / Go Home".center(210))
        ConDrive(3)
      elif Vars.DriveCount < 5:
        print("Keep Driving".center(210))
        ConDrive(4)
      elif Vars.DriveCount == 5 and "drivenToMadness" not in Achievements.Unlocked:
        Vars.ToDrive = False
        Vars.HasSave = True
        Vars.DriveCount = 0
        print("ACHIEVEMENT GET".center(210))
        print("DRIVEN TO MADNESS".center(210))
        Achievements.Unlocked.append("drivenToMadness")
        Wait(2)
        StaticImages.MainMenuImage()
  else:
    StaticImages.TheHouse()
      
      
    
def ConDrive(x):
    ContinueDriving = input(" ".rjust(193//2)).lower()
    if x == 1:
      if ContinueDriving == "keep driving" or ContinueDriving == "drive":
        Vars.DriveCount += 1
      elif ContinueDriving == "go home" or ContinueDriving == "home":
        Vars.ToDrive = False
        StaticImages.HomeImage()
      elif ContinueDriving == "investigate":
        Vars.ToDrive = False
        StaticImages.TheHouse()
      elif ContinueDriving == "skip":
        Vars.DriveCount = 5
    elif x == 2:
      if ContinueDriving == "go home" or ContinueDriving == "home":
        Vars.ToDrive = False
        StaticImages.HomeImage()
      elif ContinueDriving == "investigate":
        Vars.ToDrive = False
        StaticImages.TheHouse()
    elif x == 3:
      if ContinueDriving == "keep driving" or ContinueDriving == "drive":
        Vars.DriveCount += 1
      elif ContinueDriving == "go home" or ContinueDriving == "home":
        Vars.ToDrive = False
        StaticImages.HomeImage()
    elif x == 4:
      if ContinueDriving == "keep driving" or ContinueDriving == "drive":
        Vars.DriveCount += 1