import Vars, StaticImages, Achievements
from GeneralFunctions import Clear, Wait
def Driving():
  Vars.ToDrive = True
  while Vars.ToDrive == True:
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    print("")
    Clear(.025)
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("▏")
    print("▏")
    print("▏")
    print(" ")
    print(" ")
    Clear(.025)
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("▌")
    print("▌")
    print("▌")
    print(" ")
    print(" ")
    Clear(.025)
    print(" ")
    print(" ")
    print(" ")
    print(" ")
    print("█")
    print("█")
    print("█")
    print(" ")
    print(" ")
    Clear(.025)
    print("  ")
    print("  ")
    print("  ")
    print("▙ ")
    print("██")
    print("██")
    print("██")
    print("  ")
    print("  ")
    Clear(.025)
    print("   ")
    print("   ")
    print("▙  ")
    print("█▙ ")
    print("███")
    print("███")
    print("███")
    print("   ")
    print("   ")
    Clear(.025)
    print("    ")
    print("    ")
    print("▙   ")
    print("▁█▙ ")
    print("▕███")
    print("▕███")
    print("▁███")
    print("▙   ")
    print("▛   ")
    Clear(.025)
    print("     ")
    print("     ")
    print("█▙   ")
    print("▁▁█▙ ")
    print("▗▕███")
    print(" ▕███")
    print("▁▁███")
    print("█▙   ")
    print("█▛   ")
    Clear(.025)
    print("      ")
    print("      ")
    print("██▙   ")
    print("▁▁▁█▙ ")
    print(" ▗▕███")
    print("  ▕███")
    print("▁▁▁███")
    print("▟█▙   ")
    print("▜█▛   ")
    Clear(.025)
    print("       ")
    print("       ")
    print("███▙   ")
    print("█▁▁▁█▙ ")
    print("█ ▗▕███")
    print("█  ▕███")
    print("█▁▁▁███")
    print(" ▟█▙   ")
    print(" ▜█▛   ")
    Clear(.025)
    print("        ")
    print("        ")
    print(" ███▙   ")
    print(" █▁▁▁█▙ ")
    print("██ ▗▕███")
    print("██  ▕███")
    print("██▁▁▁███")
    print("  ▟█▙   ")
    print("  ▜█▛   ")
    Clear(.025)
    print("         ")
    print("         ")
    print("  ███▙   ")
    print("  █▁▁▁█▙ ")
    print("███ ▗▕███")
    print("███  ▕███")
    print("███▁▁▁███")
    print("   ▟█▙   ")
    print("   ▜█▛   ")
    Clear(.025)
    print("          ")
    print("          ")
    print("   ███▙   ")
    print("   █▁▁▁█▙ ")
    print("████ ▗▕███")
    print("████  ▕███")
    print("████▁▁▁███")
    print("    ▟█▙   ")
    print("    ▜█▛   ")
    Clear(.025)
    print("           ")
    print("           ")
    print("    ███▙   ")
    print("    █▁▁▁█▙ ")
    print("█████ ▗▕███")
    print("█████  ▕███")
    print("█████▁▁▁███")
    print("     ▟█▙   ")
    print("     ▜█▛   ")
    Clear(.025)
    print("            ")
    print("            ")
    print("     ███▙   ")
    print("     █▁▁▁█▙ ")
    print("██████ ▗▕███")
    print("██████  ▕███")
    print("██████▁▁▁███")
    print("      ▟█▙   ")
    print("      ▜█▛   ")
    Clear(.025)
    print("             ")
    print("             ")
    print("      ███▙   ")
    print("      █▁▁▁█▙ ")
    print("███████ ▗▕███")
    print("███████  ▕███")
    print("███████▁▁▁███")
    print("       ▟█▙   ")
    print("       ▜█▛   ")
    Clear(.025)
    print("              ")
    print("              ")
    print("       ███▙   ")
    print("       █▁▁▁█▙ ")
    print("████████ ▗▕███")
    print("████████  ▕███")
    print("████████▁▁▁███")
    print("        ▟█▙   ")
    print("        ▜█▛   ")
    Clear(.025)
    print("               ")
    print("               ")
    print("        ███▙   ")
    print("        █▁▁▁█▙ ")
    print("█████████ ▗▕███")
    print("█████████  ▕███")
    print("█████████▁▁▁███")
    print("         ▟█▙   ")
    print("         ▜█▛   ")
    Clear(.025)
    print("                ")
    print("                ")
    print("         ███▙   ")
    print("         █▁▁▁█▙ ")
    print("██████████ ▗▕███")
    print("██████████  ▕███")
    print("██████████▁▁▁███")
    print("          ▟█▙   ")
    print("          ▜█▛   ")
    Clear(.025)
    print("                 ")
    print("                 ")
    print("          ███▙   ")
    print("          █▁▁▁█▙ ")
    print("███████████ ▗▕███")
    print("███████████  ▕███")
    print("███████████▁▁▁███")
    print("           ▟█▙   ")
    print("           ▜█▛   ")
    Clear(.025)
    print("                  ")
    print("                  ")
    print("           ███▙   ")
    print("           █▁▁▁█▙ ")
    print("████████████ ▗▕███")
    print("████████████  ▕███")
    print("████████████▁▁▁███")
    print("            ▟█▙   ")
    print("            ▜█▛   ")
    Clear(.025)
    print("                   ")
    print("                   ")
    print("            ███▙   ")
    print("            █▁▁▁█▙ ")
    print("█████████████ ▗▕███")
    print("█████████████  ▕███")
    print("█████████████▁▁▁███")
    print("             ▟█▙   ")
    print("             ▜█▛   ")
    Clear(.025)
    print("                    ")
    print("                    ")
    print("             ███▙   ")
    print("             █▁▁▁█▙ ")
    print("██████████████ ▗▕███")
    print("██████████████  ▕███")
    print("██████████████▁▁▁███")
    print("▙             ▟█▙   ")
    print("▛             ▜█▛   ")
    Clear(.025)
    print("                     ")
    print("                     ")
    print("              ███▙   ")
    print("              █▁▁▁█▙ ")
    print("███████████████ ▗▕███")
    print("███████████████  ▕███")
    print("███████████████▁▁▁███")
    print("█▙             ▟█▙   ")
    print("█▛             ▜█▛   ")
    Clear(.025)
    print("                      ")
    print("                      ")
    print("               ███▙   ")
    print("               █▁▁▁█▙ ")
    print("████████████████ ▗▕███")
    print("████████████████  ▕███")
    print("████████████████▁▁▁███")
    print("▟█▙             ▟█▙   ")
    print("▜█▛             ▜█▛   ")
    Clear(.025)
    print("                       ")
    print("                       ")
    print("                ███▙   ")
    print("                █▁▁▁█▙ ")
    print("█████████████████ ▗▕███")
    print("█████████████████  ▕███")
    print("█████████████████▁▁▁███")
    print(" ▟█▙             ▟█▙   ")
    print(" ▜█▛             ▜█▛   ")
    Clear(.025)
    print("                        ")
    print("                        ")
    print("                 ███▙   ")
    print("                 █▁▁▁█▙ ")
    print("██████████████████ ▗▕███")
    print("██████████████████  ▕███")
    print("██████████████████▁▁▁███")
    print("  ▟█▙             ▟█▙   ")
    print("  ▜█▛             ▜█▛   ")
    Clear(.025)
    for frame in range(185):
      frame += 1
      print("                        ".rjust(frame+24))
      print("                        ".rjust(frame+24))
      print("                 ███▙   ".rjust(frame+24))
      print("                 █▁▁▁█▙ ".rjust(frame+24))
      print("██████████████████ ▗▕███".rjust(frame+24))
      print("██████████████████  ▕███".rjust(frame+24))
      print("██████████████████▁▁▁███".rjust(frame+24))
      print("  ▟█▙             ▟█▙   ".rjust(frame+24))
      print("  ▜█▛             ▜█▛   ".rjust(frame+24))
      Clear(.025)
    print("                       ".rjust(209))
    print("                       ".rjust(209))
    print("                 ███▙  ".rjust(209))
    print("                 █▁▁▁█▙".rjust(209))
    print("██████████████████ ▗▕██".rjust(209))
    print("██████████████████  ▕██".rjust(209))
    print("██████████████████▁▁▁██".rjust(209))
    print("  ▟█▙             ▟█▙  ".rjust(209))
    print("  ▜█▛             ▜█▛  ".rjust(209))
    Clear(.025)
    print("                      ".rjust(209))
    print("                      ".rjust(209))
    print("                 ███▙ ".rjust(209))
    print("                 █▁▁▁█".rjust(209))
    print("██████████████████ ▗▕█".rjust(209))
    print("██████████████████  ▕█".rjust(209))
    print("██████████████████▁▁▁█".rjust(209))
    print("  ▟█▙             ▟█▙ ".rjust(209))
    print("  ▜█▛             ▜█▛ ".rjust(209))
    Clear(.025)
    print("                     ".rjust(209))
    print("                     ".rjust(209))
    print("                 ███▙".rjust(209))
    print("                 █▁▁▁".rjust(209))
    print("██████████████████ ▗▕".rjust(209))
    print("██████████████████  ▕".rjust(209))
    print("██████████████████▁▁▁".rjust(209))
    print("  ▟█▙             ▟█▙".rjust(209))
    print("  ▜█▛             ▜█▛".rjust(209))
    Clear(.025)
    print("                    ".rjust(209))
    print("                    ".rjust(209))
    print("                 ███".rjust(209))
    print("                 █▁▁".rjust(209))
    print("██████████████████ ▗".rjust(209))
    print("██████████████████  ".rjust(209))
    print("██████████████████▁▁".rjust(209))
    print("  ▟█▙             ▟█".rjust(209))
    print("  ▜█▛             ▜█".rjust(209))
    Clear(.025)
    print("                   ".rjust(209))
    print("                   ".rjust(209))
    print("                 ██".rjust(209))
    print("                 █▁".rjust(209))
    print("██████████████████ ".rjust(209))
    print("██████████████████ ".rjust(209))
    print("██████████████████▁".rjust(209))
    print("  ▟█▙             ▟".rjust(209))
    print("  ▜█▛             ▜".rjust(209))
    Clear(.025)
    print("                  ".rjust(209))
    print("                  ".rjust(209))
    print("                 █".rjust(209))
    print("                 █".rjust(209))
    print("██████████████████".rjust(209))
    print("██████████████████".rjust(209))
    print("██████████████████".rjust(209))
    print("  ▟█▙             ".rjust(209))
    print("  ▜█▛             ".rjust(209))
    Clear(.025)
    print("                 ".rjust(209))
    print("                 ".rjust(209))
    print("                 ".rjust(209))
    print("                 ".rjust(209))
    print("█████████████████".rjust(209))
    print("█████████████████".rjust(209))
    print("█████████████████".rjust(209))
    print("  ▟█▙            ".rjust(209))
    print("  ▜█▛            ".rjust(209))
    Clear(.025)
    print("                ".rjust(209))
    print("                ".rjust(209))
    print("                ".rjust(209))
    print("                ".rjust(209))
    print("████████████████".rjust(209))
    print("████████████████".rjust(209))
    print("████████████████".rjust(209))
    print("  ▟█▙           ".rjust(209))
    print("  ▜█▛           ".rjust(209))
    Clear(.025)
    print("               ".rjust(209))
    print("               ".rjust(209))
    print("               ".rjust(209))
    print("               ".rjust(209))
    print("███████████████".rjust(209))
    print("███████████████".rjust(209))
    print("███████████████".rjust(209))
    print("  ▟█▙          ".rjust(209))
    print("  ▜█▛          ".rjust(209))
    Clear(.025)
    print("              ".rjust(209))
    print("              ".rjust(209))
    print("              ".rjust(209))
    print("              ".rjust(209))
    print("██████████████".rjust(209))
    print("██████████████".rjust(209))
    print("██████████████".rjust(209))
    print("  ▟█▙         ".rjust(209))
    print("  ▜█▛         ".rjust(209))
    Clear(.025)
    print("             ".rjust(209))
    print("             ".rjust(209))
    print("             ".rjust(209))
    print("             ".rjust(209))
    print("█████████████".rjust(209))
    print("█████████████".rjust(209))
    print("█████████████".rjust(209))
    print("  ▟█▙        ".rjust(209))
    print("  ▜█▛        ".rjust(209))
    Clear(.025)
    print("            ".rjust(209))
    print("            ".rjust(209))
    print("            ".rjust(209))
    print("            ".rjust(209))
    print("████████████".rjust(209))
    print("████████████".rjust(209))
    print("████████████".rjust(209))
    print("  ▟█▙       ".rjust(209))
    print("  ▜█▛       ".rjust(209))
    Clear(.025)
    print("           ".rjust(209))
    print("           ".rjust(209))
    print("           ".rjust(209))
    print("           ".rjust(209))
    print("███████████".rjust(209))
    print("███████████".rjust(209))
    print("███████████".rjust(209))
    print("  ▟█▙      ".rjust(209))
    print("  ▜█▛      ".rjust(209))
    Clear(.025)
    print("          ".rjust(209))
    print("          ".rjust(209))
    print("          ".rjust(209))
    print("          ".rjust(209))
    print("██████████".rjust(209))
    print("██████████".rjust(209))
    print("██████████".rjust(209))
    print("  ▟█▙     ".rjust(209))
    print("  ▜█▛     ".rjust(209))
    Clear(.025)
    print("         ".rjust(209))
    print("         ".rjust(209))
    print("         ".rjust(209))
    print("         ".rjust(209))
    print("█████████".rjust(209))
    print("█████████".rjust(209))
    print("█████████".rjust(209))
    print("  ▟█▙    ".rjust(209))
    print("  ▜█▛    ".rjust(209))
    Clear(.025)
    print("        ".rjust(209))
    print("        ".rjust(209))
    print("        ".rjust(209))
    print("        ".rjust(209))
    print("████████".rjust(209))
    print("████████".rjust(209))
    print("████████".rjust(209))
    print("  ▟█▙   ".rjust(209))
    print("  ▜█▛   ".rjust(209))
    Clear(.025)
    print("       ".rjust(209))
    print("       ".rjust(209))
    print("       ".rjust(209))
    print("       ".rjust(209))
    print("███████".rjust(209))
    print("███████".rjust(209))
    print("███████".rjust(209))
    print("  ▟█▙  ".rjust(209))
    print("  ▜█▛  ".rjust(209))
    Clear(.025)
    print("      ".rjust(209))
    print("      ".rjust(209))
    print("      ".rjust(209))
    print("      ".rjust(209))
    print("██████".rjust(209))
    print("██████".rjust(209))
    print("██████".rjust(209))
    print("  ▟█▙ ".rjust(209))
    print("  ▜█▛ ".rjust(209))
    Clear(.025)
    print("     ".rjust(209))
    print("     ".rjust(209))
    print("     ".rjust(209))
    print("     ".rjust(209))
    print("█████".rjust(209))
    print("█████".rjust(209))
    print("█████".rjust(209))
    print("  ▟█▙".rjust(209))
    print("  ▜█▛".rjust(209))
    Clear(.025)
    print("    ".rjust(209))
    print("    ".rjust(209))
    print("    ".rjust(209))
    print("    ".rjust(209))
    print("████".rjust(209))
    print("████".rjust(209))
    print("████".rjust(209))
    print("  ▟█".rjust(209))
    print("  ▜█".rjust(209))
    Clear(.025)
    print("   ".rjust(209))
    print("   ".rjust(209))
    print("   ".rjust(209))
    print("   ".rjust(209))
    print("███".rjust(209))
    print("███".rjust(209))
    print("███".rjust(209))
    print("  ▟".rjust(209))
    print("  ▜".rjust(209))
    Clear(.025)
    print("  ".rjust(209))
    print("  ".rjust(209))
    print("  ".rjust(209))
    print("  ".rjust(209))
    print("██".rjust(209))
    print("██".rjust(209))
    print("██".rjust(209))
    print("  ".rjust(209))
    print("  ".rjust(209))
    Clear(.025)
    print(" ".rjust(209))
    print(" ".rjust(209))
    print(" ".rjust(209))
    print(" ".rjust(209))
    print("█".rjust(209))
    print("█".rjust(209))
    print("█".rjust(209))
    print(" ".rjust(209))
    print(" ".rjust(209))
    Clear(.025)
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    print("".rjust(209))
    Clear(.025)
    if Vars.DriveCount == 0:
      print("You hear strange noises coming from a house nearby.".center(210))
      print("Keep Driving / Investigate / Go Home".center(210))
    elif Vars.DriveCount <= 3:
      print("Keep Driving / Go Home".center(210))
    elif Vars.DriveCount < 5:
      print("Keep Driving".center(210))
    elif Vars.DriveCount == 5:
      print("ACHIEVEMENT GET".center(210))
      print("DRIVEN TO MADNESS".center(210))
      Achievements.Unlocked.append("drivenToMadness")
      Wait(2)
      Vars.HasSave = True
      StaticImages.MainMenuImage()
      
    ContinueDriving = input("".rjust(193//2)).lower()
    if ContinueDriving == "keep driving" or ContinueDriving == "drive":
      Vars.DriveCount += 1
    elif ContinueDriving == "go home" or ContinueDriving == "home":
      Vars.ToDrive = False
    elif ContinueDriving == "investigate":
      Vars.ToDrive = False
    elif ContinueDriving == "skip":
      Vars.DriveCount = 5
    
    